# TEMA - Cambiar entre ayu-mirage o ayu-light
include themes/ayu-mirage.conf

# Ligaduras
disable_ligatures never

# Apariencia #
cursor_blink_interval 0
window_padding_width 4
# Hide tab bar in ubuntu
#hide_window_decorations True 
# Background opacity
background_opacity 0.90


# Clipboard
copy_on_select yes

# URLs clickeables con Ctrl+Click
detect_urls yes

# Soporte para imágenes
allow_remote_control yes

# Tabs
tab_bar_style powerline
tab_bar_edge top

# Atajos - Tabs
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab

# Atajos - Tamanio
map ctrl+shift+minus change_font_size all -2.0
map ctrl+shift+backspace change_font_size all 0


# Atajos - Ventanas
map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

# Atajos - Splits
#map ctrl+shift+minus launch --location=hsplit
map ctrl+shift+backslash launch --location=vsplit

# Atajos - Clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
